name: dev21maker_s_application13
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.4.4 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  google_sign_in: ^5.0.7
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.0.4
  dio: ^5.5.0+1
  google_sign_in_web:
  flutter_dotenv:
  dio:
  firebase_core:
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  generate: true
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoBold.ttf
          weight: 700
